### 文件变量
@host=localhost:8080
@username=jinyong
@password=123456
@jwt=eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjpudWxsLCJpZCI6bnVsbCwiZXhwIjoxNzEzMDMwOTgwLCJ1c2VybmFtZSI6ImppbnlvbmcifQ.Du_KL1z6RlfawWpCVNEn7FOgAL00sArJ-qD8xRgrABM
### 登录功能测试

POST /login HTTP/1.1
Host: {{ host }}
Content-Type: application/json

{
    "username":"{{username}}",
    "password":"{{password}}"
}

### 使用 > 语法
# 绝对路径：直接查找
# 相对路径：会以 *.http 文件所在路径 + 项目路径查找

POST /login HTTP/1.1
Host: {{ host }}
Content-Type: application/json

< ./res/login.json


